# Create Person
POST http://localhost:8080/ca1_war_exploded/api/person/
Content-Type: application/json

{
  "email": "JamesBond@mail.dk",
  "firstName": "James",
  "lastName": "Bond",
  "addressDTO": {

    "street": "Bondvej",
    "additionalInfo": "2 tv",
    "cityInfoDTO": {

      "zipCode": "2500",
      "city": "Valby"
    }
  },
  "phoneList": [
    {
    "number": "007",
    "description": "Home"
  }
  ],
  "hobbyDTOList": [
    {
      "id": 1
    }
  ]
}

###
# Get info from person with ID
GET http://localhost:8080/ca1_war_exploded/api/person/29
Content-Type: application/json

###
# Update person with ID
PUT http://localhost:8080/ca1_war_exploded/api/person/1
Content-Type: application/json

{
  "email": "JimmyBondz@mail.dk",
  "firstName": "Jimmy",
  "lastName": "Bondz",
  "addressDTO": {

    "street": "Bonzaivej 65",
    "additionalInfo": "21 tv",
    "cityInfoDTO": {

      "zipCode": "2500",
      "city": "Valby"
    }
  },
  "phoneList": [
    {
      "number": "007",
      "description": "Home"
    },
    {
      "number": "12245",
      "description": "Work"
    }
  ],
  "hobbyDTOList": [
    {
      "id": 1
    },
    {
      "id": 3
    }
  ]
}

###
# Get person with phone number
GET http://localhost:8080/ca1_war_exploded/api/person/phone/36164523
Content-Type: application/json

###
# Get persons with given hobby
GET http://localhost:8080/ca1_war_exploded/api/person/hobby/1
Content-Type: application/json

###

#PUT http://localhost:8080/ca1_war_exploded/api/person/removehobbies/20
#Content-Type: application/json